apiVersion: v1
kind: ConfigMap
metadata:
  name: web
data:
  nginx.conf: |
    proxy_http_version 1.1;

    location /api/ {
        proxy_pass http://backend:8080/;
    }

    location /health {
        stub_status on;
        access_log off;
    }

    # ✅ This block serves your React frontend and static assets
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
    project: roboshop
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
      project: roboshop
      tier: web
  template:
    metadata:
      labels:
        name: web
        project: roboshop
        tier: web
    spec:
      containers:
      - name: web
        image: hitesh2201/web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/default.d/expense.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    name: web
    project: roboshop
    tier: web
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
